### ISSUE TITLE
HTML: the <small> tag line

### ISSUE THREAD

**Issue by Denizmelek** [Denizmelek/My_Weather_App#1]
The <small> tagline - `Open-source code, by Denizmelek ©` should be written behind the weather container card.
To design the weather container has been used from the Bootstrap CSS framework.

I have tried to solve this issue by using the `position` CSS property to control and change the element's position in a document. But yet not succeeded. WIP.

**Comment by bensonOSei** [comment]
Can I try my hands on this?

**Comment by Denizmelek** [comment]
> Can I try my hands on this?

Hi @bensonOSei, I hope you are doing well,

Could you advise me?
This is actually my homework and I'm stuck on this detail. But I would try it on my own at first)
I appreciate that you have asked 🙏🏽

**Comment by bensonOSei** [comment]
Okay ... I'm going through the code now

**Comment by Denizmelek** [comment]
> Okay ... I'm going through the code now

You can work on your own. If I'm not mistaken, it will not affect my code!?

**Comment by bensonOSei** [comment]
No... I'll create a pull request and you'll see the changes I've made

**Comment by Denizmelek** [comment]
Let me try to figure it out first) I will work on it a bit later.
